name: Node.js CI

on: [push]

jobs:
  check-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
          run_install: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run prettier check
        run: pnpm check:format

  check-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
          run_install: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run next lint
        run: pnpm lint

  build:
    runs-on: ubuntu-latest

    needs: [check-lint, check-format]

    strategy:
      matrix:
        node-version:
          - 18.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
          run_install: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build the site
        run: pnpm build
      - name: Build the site
        run: pnpm build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: blog-static
          path: out
          retention-days: 7
