name: Node.js CI

on: [push]

jobs:
  check-format:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
          run_install: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run prettier check
        run: pnpm check:format
